version: '3'

services:
  entreamientodb:
    image: postgres
    container_name: entreamientodb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mateu
      - POSTGRES_DB=entreamientodb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
