version: '3'

services:
 leaguesdb:
    image: postgres
    container_name: leaguesdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mateu
      - POSTGRES_DB=leaguesdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
